"""Build every file the ESP32 tests need into tests/build/device_upload/.

- policy_network.mpy : generated by simtoreal (its default output: precompiled MicroPython)
- main_generated.py  : the main.py simtoreal generates from library/simtoreal/config.yaml
                       (renamed so it does not replace the board's own main.py)
- test_vectors.py    : inputs + the outputs PyTorch gives for them (ground truth for test D1)
- imu.py, servo.py   : the library's own drivers (library/simtoreal/...)
- the test scripts   : tests/device/*.py

Also prepares the optional Arduino C benchmark in tests/build/arduino/policy_bench/.

Run from the repo root:  python tests/host/make_device_files.py
"""

import shutil

import numpy as np
from stable_baselines3 import PPO

import common

UPLOAD = common.BUILD / "device_upload"
ARDUINO = common.BUILD / "arduino" / "policy_bench"
N_VECTORS = 20


def make_test_vectors(model) -> tuple:
    rng = np.random.default_rng(1)
    random_obs = rng.uniform(common.OBS_LOW, common.OBS_HIGH, size=(N_VECTORS // 2, 5)).astype(np.float32)
    rollout_obs = common.collect_rollout_observations(model, episodes_per_case=1)
    pick = rng.choice(len(rollout_obs), size=N_VECTORS - len(random_obs), replace=False)
    obs = np.vstack([random_obs, rollout_obs[pick]])
    expected = common.torch_actor_mean(model, obs)
    return obs, expected


def fmt_rows(rows, suffix=""):
    return ",\n".join("    [" + ", ".join(f"{x:.8f}{suffix}" for x in r) + "]" for r in rows)


def main():
    artifacts = common.build_artifacts()
    model = PPO.load(str(common.MODEL), device="cpu")

    if UPLOAD.exists():
        shutil.rmtree(UPLOAD)
    UPLOAD.mkdir(parents=True)

    shutil.copy(artifacts["mpy"], UPLOAD / "policy_network.mpy")
    shutil.copy(artifacts["main"], UPLOAD / "main_generated.py")

    obs, expected = make_test_vectors(model)
    (UPLOAD / "test_vectors.py").write_text(
        "# Auto-generated by tests/host/make_device_files.py - PyTorch ground truth for test D1\n"
        f"OBS = [\n{fmt_rows(obs)}\n]\n\nEXPECTED = [\n{fmt_rows(expected)}\n]\n"
    )

    shutil.copy(common.REPO / "library/simtoreal/sensors/imu.py", UPLOAD / "imu.py")
    shutil.copy(common.REPO / "library/simtoreal/actuators/servo.py", UPLOAD / "servo.py")
    for script in (common.TESTS / "device").glob("*.py"):
        shutil.copy(script, UPLOAD / script.name)

    # Optional Arduino (C header) benchmark: needs Arduino IDE and replaces MicroPython on the board.
    ARDUINO.mkdir(parents=True, exist_ok=True)
    shutil.copy(artifacts["h"], ARDUINO / "policy_network.h")
    shutil.copy(common.TESTS / "optional_arduino_c/policy_bench/policy_bench.ino", ARDUINO / "policy_bench.ino")
    (ARDUINO / "test_vectors.h").write_text(
        "// Auto-generated by tests/host/make_device_files.py - PyTorch ground truth\n"
        f"#define NUM_TESTS {len(obs)}\n"
        f"const float test_obs[NUM_TESTS][5] = {{\n{fmt_rows(obs, 'f').replace('[', '{').replace(']', '}')}\n}};\n"
        f"const float test_expected[NUM_TESTS][2] = {{\n{fmt_rows(expected, 'f').replace('[', '{').replace(']', '}')}\n}};\n"
    )

    print("\nFiles for the ESP32 (upload this whole folder to the board as /sim2real_tests):")
    for f in sorted(UPLOAD.iterdir()):
        print(f"  {f.relative_to(common.REPO)}  ({f.stat().st_size} bytes)")
    print(f"\nOptional Arduino sketch folder: {ARDUINO.relative_to(common.REPO)}")


if __name__ == "__main__":
    main()
